# Generated by Django 2.1.5 on 2019-02-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('picture_url', models.CharField(max_length=50)),
                ('cv_url', models.CharField(max_length=50)),
            ],
        ),
    ]
